// This file is generated by tauri-specta during `tauri dev` in debug builds.
// It is intentionally committed as a bootstrap fallback until first generation.

import { invoke } from "@tauri-apps/api/core";

export const greet = (name: string) => invoke<string>("greet", { name });
