/**
 * This file was auto-generated by pocketbase-zod-schema.
 * Do not modify it manually.
 */

import PocketBase from "pocketbase";
import type { RecordService } from "pocketbase";
import type { RecordModel } from "pocketbase";

export interface PostsRecord {
  id: string;
  created: string;
  updated: string;
  collectionId: string;
  collectionName: "posts";
  title: string;
  slug: string;
  content: string;
  excerpt: string;
  published: boolean;
  status: "draft" | "published" | "archived";
  views?: number;
  author: string;
  tags: string[];
}

export interface PostsResponse extends PostsRecord {
  expand?: {
    author?: RecordModel;
    tags?: RecordModel[];
  };
}

export type CollectionResponses = {
  posts: PostsResponse;
};

export interface TypedPocketBase extends PocketBase {
  collection(idOrName: "posts"): RecordService<PostsResponse>;
}
